GET {{qyoga_url}}/exercises HTTP/1.1

###

PUT {{qyoga_url}}/exercises/1 HTTP/1.1
Content-Type: application/json

{
  "id": 1,
  "name": "Вытяжение внешней поверхности стопы2",
  "description": "На уровне щиколоток завязать ремешок (без крупных пряжек). Упражнение можно выполнять без ремешка, в этом случае нужно удерживать пятки рядом друг с другом силой мышц.\nВстать на колени (колени вместе, стопы вместе) и сесть ягодицами на пятки. Расправить руками пальцы стоп, все пальцы должны быть направлены назад. Тыльные стороны стопы прижать к полу. Мизинцы вытягивать назад, стараться сделать их длиннее больших пальцев.\nНаходиться в позе 3-5 минут. Если появляется в стопах дискомфорт, выходить раньше.\nПри выходе из позы сначала подвернуть пальцы на стопах, сесть на пятки и потом аккуратно вставать.2",
  "instructions": "На уровне щиколоток завязать ремешок (без крупных пряжек). Упражнение можно выполнять без ремешка, в этом случае нужно удерживать пятки рядом друг с другом силой мышц.\nВстать на колени (колени вместе, стопы вместе) и сесть ягодицами на пятки. Расправить руками пальцы стоп, все пальцы должны быть направлены назад. Тыльные стороны стопы прижать к полу. Мизинцы вытягивать назад, стараться сделать их длиннее больших пальцев.\nНаходиться в позе 3-5 минут. Если появляется в стопах дискомфорт, выходить раньше.\nПри выходе из позы сначала подвернуть пальцы на стопах, сесть на пятки и потом аккуратно вставать.2",
  "duration": 12.000000000,
  "tags": [
    {
      "tag": "стопы"
    },
    {
      "tag": "грудной отдел"
    },
    {
      "tag": "поясница2"
    }
  ],
  "images": [
    "images/1"
  ]
}
